# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\"\x1f\n\x0f\x41nalysisRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\"\n\x10\x41nalysisResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2<\n\x06Worker\x12\x32\n\x0b\x41nalyzeData\x12\x10.AnalysisRequest\x1a\x11.AnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISREQUEST']._serialized_start=14
  _globals['_ANALYSISREQUEST']._serialized_end=45
  _globals['_ANALYSISRESPONSE']._serialized_start=47
  _globals['_ANALYSISRESPONSE']._serialized_end=81
  _globals['_WORKER']._serialized_start=83
  _globals['_WORKER']._serialized_end=143
# @@protoc_insertion_point(module_scope)
